### ISSUE TITLE
Error when editing and saving booking

### ISSUE THREAD

**Issue by d-nagy** [ben-willis/grey-jcr#52]
During formal bookings today, this issue came up whenever one would edit their booking and press save. After pressing save, the following error message appears:

```
Cannot read property 'name' of null
TypeError: Cannot read property 'name' of null
    at /usr/app/src/routes/events.js:171:40
    at tryCatcher (/usr/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/app/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
I think it is referring to the following section of ```src/routes/events.js```:
```
.then(function(user) {
	var name = (booking.username !== null) ? booking.username : booking.guestname;
	return user.setDebtForBooking(ticket.name, "Ticket for "+name, amount, booking.id);
})
```
and it appears that ```ticket``` is null, and so trying to use ```ticket.name``` is returning an error.

**Comment by ben-willis** [comment]
Hmmm not entirely sure what would be causing this. I've made a couple of changes to tidy up the code here #53 (feel free to merge this when ready) but I'm not sure why this problem would appear now.

**Comment by ben-willis** [comment]
Also its worth noting the booking choices are being updated but the debts aren't being updated.

**Comment by d-nagy** [comment]
Do you mean the debt incurred for different meal choices?

**Comment by ben-willis** [comment]
Yep. So the CSV with all the bookings has the correct options in it but the debts may be inacurate if the meal options have a price.

**Comment by d-nagy** [comment]
OK - luckily they didn't have a price this time, so we didn't notice that and won't affect anything for this particular booking. Is it not updating the debts even with your fix?

**Comment by ben-willis** [comment]
Yeah my fix works so I'll merge it now and close this issue.
