### ISSUE TITLE
Error when creating folders in Files

### ISSUE THREAD

**Issue by d-nagy** [ben-willis/grey-jcr#63]
The JCR Secretary has informed me of an error encountered when trying to create a folder in the Files page. 

I have been sent the following screenshot of the error:

![folder_creation_error](https://user-images.githubusercontent.com/36937255/41196320-f88e4c60-6c34-11e8-935e-89e2345509ff.jpeg)

I'm having trouble recreating this error both on the live website and my local version, including when I add myself as secretary (on both local and live versions of the website). I'm also unsure exactly which part of the code throws this error.

Based on my testing, this may be something on the part of the secretary, as I cannot recreate it at all, but it would be good to confirm this with someone else.

**Comment by d-nagy** [comment]
The error as text:

**select * from "folders" where "id" = $1 limit $2 - invalid input syntax for integer: "NaN"**
```
error: select * from "folders" where "id" = $1 limit $2 - invalid input syntax for integer: "NaN"
    at Connection.parseE (/usr/app/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/usr/app/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/usr/app/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
```

**Comment by d-nagy** [comment]
This is pretty unreproducable and we decided (the Secretary and I) to just clear the Secretary folders and reupload everything. There's nothing much we can do about this now.
